import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoTitle from "./components/LogoTitle";
import Navbar from "./components/Navbar";
import SearchBar from "./components/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased p-3`}>

        {/* Top Navigation */}
        <div className="bg-white h-14 flex justify-center items-center gap-2">
          <LogoTitle />
          <Navbar />
          <SearchBar />
        </div>

        {/* Main Content */}
        {children}

      </body>
    </html>
  );
}
